package com.threerings.opengl.gui;

/**
 * Reflection wrappers for game internals.
 *
 * All obfuscated names live in MappingsNames (generated by Patcher at build time).
 * Constants there are `static final String`, so javac inlines their values into every
 * caller — zero runtime cost.  This class only provides convenience wrappers that
 * do the reflection calls so callers stay readable.
 */
public class Mappings extends MappingsNames {

    // ── Forge window ──────────────────────────────────────────────────────────

    public static Object getCtx(Object forgePanel) {
        try {
            java.lang.reflect.Field f = forgePanel.getClass().getDeclaredField(FORGE_CTX_FIELD);
            f.setAccessible(true);
            return f.get(forgePanel);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static void setForgeItem(Object forgePanel, Object item) {
        try {
            java.lang.reflect.Field f = forgePanel.getClass().getDeclaredField(FORGE_ITEM_FIELD);
            f.setAccessible(true);
            f.set(forgePanel, item);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static void callForgeUpgrade(Object forgePanel) {
        try {
            java.lang.reflect.Method m = forgePanel.getClass().getDeclaredMethod(FORGE_UPGRADE_METHOD);
            m.setAccessible(true);
            m.invoke(forgePanel);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static boolean isForgeBtnEnabled(Object forgePanel) {
        try {
            java.lang.reflect.Field f = forgePanel.getClass().getDeclaredField(FORGE_BTN_FIELD);
            f.setAccessible(true);
            Object btn = f.get(forgePanel);
            return (Boolean) btn.getClass().getMethod("isEnabled").invoke(btn);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static int getForgeLevel(Object forgePanel) {
        try {
            java.lang.reflect.Field f = forgePanel.getClass().getDeclaredField(FORGE_LEVEL_FIELD);
            f.setAccessible(true);
            return f.getInt(forgePanel);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static void setForgeLevel(Object forgePanel, int level) {
        try {
            java.lang.reflect.Field f = forgePanel.getClass().getDeclaredField(FORGE_LEVEL_FIELD);
            f.setAccessible(true);
            f.setInt(forgePanel, level);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static Object getForgeListenerPanel(Object listener) {
        try {
            java.lang.reflect.Field f = listener.getClass().getDeclaredField(FORGE_LISTENER_PANEL_FIELD);
            f.setAccessible(true);
            return f.get(listener);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static Object getComponent(Object forgePanel, String name) {
        try { return forgePanel.getClass().getMethod("getComponent", String.class).invoke(forgePanel, name); }
        catch (Exception e) { return null; }
    }

    public static void clickButton(Object btn) {
        try { btn.getClass().getMethod("doClick").invoke(btn); } catch (Exception e) {}
    }

    // ── Context / player ─────────────────────────────────────────────────────

    public static Object getConfigManager(Object ctx) {
        try { return ctx.getClass().getMethod(CONFIG_MANAGER_METHOD).invoke(ctx); }
        catch (Exception e) { throw new RuntimeException(e); }
    }

    public static Object getPlayerObject(Object ctx) {
        try {
            java.lang.reflect.Method m = ctx.getClass().getDeclaredMethod(PLAYER_OBJECT_METHOD);
            m.setAccessible(true);
            return m.invoke(ctx);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static java.lang.Iterable getPlayerItems(Object playerObject) {
        try { return (java.lang.Iterable) playerObject.getClass().getField("items").get(playerObject); }
        catch (Exception e) { throw new RuntimeException(e); }
    }

    /** This client's own crown balance (`PlayerObject.crowns`, a public int), or -1 if unreadable. */
    public static int getCrowns(Object ctx) {
        try {
            Object po = getPlayerObject(ctx);
            if (po == null) return -1;
            return po.getClass().getField("crowns").getInt(po);
        } catch (Exception e) { return -1; }
    }

    public static long[] getPlayerEquipment(Object playerObject) {
        try { return (long[]) playerObject.getClass().getField("equipment").get(playerObject); }
        catch (Exception e) { throw new RuntimeException(e); }
    }

    public static String getKnightName(Object playerObject) {
        // Historic behavior: the ACCOUNT username (forge-log attribution). The 0820
        // game update REMOVED PlayerObject.username outright — the first real-named
        // member ever lost to an update — so fall back to the (stable, real-named)
        // knight field rather than degrading every forge row to "Unknown". Rows
        // logged after 2026-08-20 therefore attribute by KNIGHT name.
        try {
            Object name = playerObject.getClass().getField("username").get(playerObject);
            if (name != null)
                return name.toString();
        } catch (Exception ignored) {
        }
        try {
            Object name = playerObject.getClass().getField("knight").get(playerObject);
            return name != null ? name.toString() : "Unknown";
        } catch (Exception e) { return "Unknown"; }
    }

    /**
     * The character's KNIGHT name (real-named {@code PlayerObject.knight} field) —
     * what party invites and PartyObject member lookups key on. NOT the account
     * username: {@code getKnightName} reads that (kept as-is — the forge log has
     * always attributed by username).
     */
    public static String getKnightCharacterName(Object playerObject) {
        try {
            Object name = playerObject.getClass().getField("knight").get(playerObject);
            return name != null ? name.toString() : null;
        } catch (Exception e) { return null; }
    }

    public static Object getClientManager(Object ctx) {
        try {
            java.lang.reflect.Method m = ctx.getClass().getDeclaredMethod(CLIENT_MANAGER_METHOD);
            m.setAccessible(true);
            return m.invoke(ctx);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static Object getItemService(Object clientManager) {
        try { return getService(clientManager, Class.forName(ITEM_SERVICE_CLASS)); }
        catch (Exception e) { throw new RuntimeException(e); }
    }

    public static Object getService(Object clientMgr, Class<?> serviceClass) {
        // Search all methods (declared + inherited) for one that takes a single Class
        // param — and TRY each candidate rather than trusting the first: getMethods()
        // order is unspecified, and a candidate can THROW in bad client states
        // (relog, character select). Skipping a throwing candidate instead of dying
        // is the hardening that first landed in AuctionBot's private copy; it lives
        // here so every caller (PvP, feeder, consumables, forge, joiner) gets it.
        boolean invokedAny = false;
        for (java.lang.reflect.Method m : clientMgr.getClass().getMethods()) {
            Class<?>[] p = m.getParameterTypes();
            if (p.length == 1 && p[0] == Class.class) {
                m.setAccessible(true);
                try {
                    Object s = m.invoke(clientMgr, serviceClass);
                    invokedAny = true;
                    if (s != null) return s;
                } catch (Exception ignored) { }
            }
        }
        if (invokedAny)
            return null; // resolvable, but this service isn't registered right now (e.g. logged off)
        throw new RuntimeException("Cannot find service provider method on "
            + clientMgr.getClass().getName());
    }

    // ── LevelItem ─────────────────────────────────────────────────────────────

    public static boolean isLevelItem(Object obj) {
        return obj != null && obj.getClass().getName().endsWith("LevelItem");
    }

    public static boolean isUpgradable(Object levelItem, Object configMgr) {
        try {
            Class<?> cfgClass = Class.forName(CONFIG_MANAGER_CLASS);
            java.lang.reflect.Method m = levelItem.getClass().getDeclaredMethod(
                ITEM_UPGRADABLE_METHOD, cfgClass);
            m.setAccessible(true);
            return (Boolean) m.invoke(levelItem, configMgr);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static long getItemOid(Object levelItem) {
        try {
            return (Long) levelItem.getClass().getMethod(ITEM_OID_METHOD).invoke(levelItem);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static String getItemName(Object levelItem) {
        try {
            return (String) levelItem.getClass().getMethod(ITEM_NAME_METHOD).invoke(levelItem);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static int getItemLevel(Object levelItem) {
        try {
            java.lang.reflect.Method m = levelItem.getClass().getDeclaredMethod(ITEM_LEVEL_METHOD);
            m.setAccessible(true);
            return (Integer) m.invoke(levelItem);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static Object getItemConfig(Object levelItem, Object configMgr) {
        try {
            Class<?> cfgMgrClass    = Class.forName("com.threerings.config.ConfigManager");
            Class<?> levelCfgClass  = Class.forName("com.threerings.projectx.item.config.ItemConfig$Level");
            for (java.lang.reflect.Method m : levelItem.getClass().getMethods()) {
                Class<?>[] p = m.getParameterTypes();
                if (p.length == 2 && p[0] == Class.class && cfgMgrClass.isAssignableFrom(p[1])) {
                    return m.invoke(levelItem, levelCfgClass, configMgr);
                }
            }
            return null;
        } catch (Exception e) { return null; }
    }

    public static int getItemConfigRarity(Object config) {
        try { return config.getClass().getField("rarity").getInt(config); }
        catch (Exception e) { throw new RuntimeException(e); }
    }

    // ── Service calls ─────────────────────────────────────────────────────────

    public static void callForgeService(Object itemService, long oid, int level, Object listener) {
        try {
            Class<?> listenerClass = Class.forName(RESULT_LISTENER_CLASS);
            itemService.getClass().getMethod(SERVICE_FORGE_METHOD, long.class, int.class, listenerClass)
                .invoke(itemService, oid, level, listener);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    /** Used by the Patcher ExprEditor to wrap the game's own forge listener with tracking. */
    public static void forgeWithTracking(Object svc, long oid, int crystals, int lvl, Object orig, Object ctx) {
        Object po = getPlayerObject(ctx);
        int starLevel = getItemStarLevel(po, oid, getConfigManager(ctx));
        callForgeServiceDirect(svc, oid, crystals, lvl,
            createChainingForgeListener(orig, oid, lvl, crystals, starLevel, ctx));
    }

    public static String getCrystalName(int starLevel) {
        switch (starLevel) {
            case 0: return "Cracked Fire Crystal";
            case 1: return "Dim Fire Crystal";
            case 2: return "Warm Fire Crystal";
            case 3: return "Glowing Fire Crystal";
            case 4: return "Shining Fire Crystal";
            case 5: return "Radiant Fire Crystal";
            default: return "Unknown Crystal";
        }
    }

    public static int getItemStarLevel(Object playerObject, long oid, Object configMgr) {
        try {
            for (Object item : getPlayerItems(playerObject)) {
                if (isLevelItem(item) && getItemOid(item) == oid) {
                    Object cfg = getItemConfig(item, configMgr);
                    if (cfg != null) return getItemConfigRarity(cfg);
                    break;
                }
            }
        } catch (Exception e) {}
        return 0;
    }

    /** Calls the 4-param forge service: a(oid, crystals, itemLevel, ResultListener).
     *  This is what the ForgeWindow's SX() calls — without any GL-dependent UI creation. */
    public static void callForgeServiceDirect(Object itemService, long oid, int crystals, int itemLevel, Object listener) {
        try {
            Class<?> listenerClass = Class.forName(RESULT_LISTENER_CLASS);
            for (java.lang.reflect.Method m : itemService.getClass().getMethods()) {
                Class<?>[] p = m.getParameterTypes();
                if (p.length == 4 && p[0] == long.class && p[1] == int.class
                        && p[2] == int.class && p[3] == listenerClass) {
                    m.invoke(itemService, oid, crystals, itemLevel, listener);
                    return;
                }
            }
            throw new RuntimeException("Cannot find 4-param forge service method on " + itemService.getClass());
        } catch (RuntimeException e) { throw e; }
        catch (Exception e) { throw new RuntimeException(e); }
    }

    public static int getItemRawLevel(Object levelItem) {
        return getItemLevel(levelItem);
    }

    // ── Stage heat projection ─────────────────────────────────────────────────

    /** Returns _oid from the player's DObject (walks superclass chain). */
    public static int getPlayerOid(Object playerObject) {
        Class<?> cls = playerObject.getClass();
        while (cls != null) {
            try {
                java.lang.reflect.Field f = cls.getDeclaredField("_oid");
                f.setAccessible(true);
                return f.getInt(playerObject);
            } catch (NoSuchFieldException ignored) {
                cls = cls.getSuperclass();
            } catch (Exception e) {
                return -1;
            }
        }
        return -1;
    }

    private static final int[] EQUIP_SLOTS = {0, 1, 2, 6, 7, 8, 9};

    /**
     * Returns a bitmask of levels 1-9 for which all currently-equipped 0* slots have a
     * matching 0* item available (already equipped or unused in inventory).
     * Bit L (1 << L) is set if a full set at level L exists.
     * AND-ing masks across all accounts then finding the highest set bit gives the best
     * common level.
     */
    public static int computeAvailableLevelMask(Object ctx, Object po) {
        try {
            long[] equipped = getPlayerEquipment(po);
            Object cfgManager = getConfigManager(ctx);

            // Collect item names for each equipped 0* slot.
            String[] slotNames = new String[EQUIP_SLOTS.length];
            long[]   slotOids  = new long[EQUIP_SLOTS.length];
            int checkedSlots = 0;
            for (int si = 0; si < EQUIP_SLOTS.length; si++) {
                int slot = EQUIP_SLOTS[si];
                if (slot >= equipped.length || equipped[slot] <= 0) continue;
                for (Object item : getPlayerItems(po)) {
                    if (!isLevelItem(item)) continue;
                    if (getItemOid(item) != equipped[slot]) continue;
                    Object cfg = getItemConfig(item, cfgManager);
                    if (cfg == null || getItemConfigRarity(cfg) != 0) break;
                    slotNames[si] = getItemName(item);
                    slotOids[si]  = equipped[slot];
                    checkedSlots++;
                    break;
                }
            }
            if (checkedSlots == 0) return 0;

            java.util.List<Object> allItems = new java.util.ArrayList<>();
            for (Object item : getPlayerItems(po)) {
                if (isLevelItem(item)) allItems.add(item);
            }

            int mask = 0;
            for (int L = 0; L <= 8; L++) {
                boolean allFound = true;
                java.util.Set<Long> used = new java.util.HashSet<>();
                for (long oid : equipped) if (oid > 0) used.add(oid);

                for (int si = 0; si < EQUIP_SLOTS.length; si++) {
                    if (slotNames[si] == null) continue;
                    // Already at target level — slot satisfied, OID already in used set.
                    boolean currentIsL = false;
                    for (Object item : allItems) {
                        if (getItemOid(item) == slotOids[si] && getItemRawLevel(item) == L) {
                            currentIsL = true;
                            break;
                        }
                    }
                    if (currentIsL) continue;
                    // Find an unused inventory item at level L of the same type.
                    boolean found = false;
                    for (Object item : allItems) {
                        if (getItemRawLevel(item) != L) continue;
                        if (!getItemName(item).equals(slotNames[si])) continue;
                        Object cfg = getItemConfig(item, cfgManager);
                        if (cfg == null || getItemConfigRarity(cfg) != 0) continue;
                        long oid = getItemOid(item);
                        if (used.contains(oid)) continue;
                        used.add(oid);
                        found = true;
                        break;
                    }
                    if (!found) { allFound = false; break; }
                }
                if (allFound) mask |= (1 << L);
            }
            return mask;
        } catch (Exception e) {
            ForgeTracker.debug("computeAvailableLevelMask ERROR: " + e);
            return 0;
        }
    }

    /**
     * For each equipped 0* slot, if the item there is not already at targetLevel, finds an
     * unused 0* item at targetLevel of the same type and equips it.
     */
    public static void equipTargetLevel(Object ctx, Object po, int targetLevel) {
        try {
            long[] equipped = getPlayerEquipment(po);
            Object cfgManager = getConfigManager(ctx);
            java.util.Set<Long> newlyEquipped = new java.util.HashSet<>();
            java.util.Set<Long> equippedOids  = new java.util.HashSet<>();
            for (long oid : equipped) if (oid > 0) equippedOids.add(oid);

            for (int slot : EQUIP_SLOTS) {
                if (slot >= equipped.length || equipped[slot] <= 0) continue;
                Object current = null;
                for (Object item : getPlayerItems(po)) {
                    if (!isLevelItem(item)) continue;
                    if (getItemOid(item) != equipped[slot]) continue;
                    current = item;
                    break;
                }
                if (current == null) continue;
                Object cfg = getItemConfig(current, cfgManager);
                if (cfg == null || getItemConfigRarity(cfg) != 0) continue;
                if (getItemRawLevel(current) == targetLevel) continue;
                String targetName = getItemName(current);
                for (Object candidate : getPlayerItems(po)) {
                    if (!isLevelItem(candidate)) continue;
                    if (getItemRawLevel(candidate) != targetLevel) continue;
                    if (!getItemName(candidate).equals(targetName)) continue;
                    Object candidateCfg = getItemConfig(candidate, cfgManager);
                    if (candidateCfg == null || getItemConfigRarity(candidateCfg) != 0) continue;
                    long oid = getItemOid(candidate);
                    if (equippedOids.contains(oid) || newlyEquipped.contains(oid)) continue;
                    Object clientManager = getClientManager(ctx);
                    Object itemService = getItemService(clientManager);
                    final boolean[] done = {false};
                    Object listener = createConfirmListenerProxy(done, "CoordEquip");
                    callEquipService(itemService, oid, slot, listener);
                    int loops = 0;
                    while (!done[0] && loops++ < 60) {
                        try { Thread.sleep(50); } catch (Exception ignored) {}
                    }
                    try { Thread.sleep(75 + new java.util.Random().nextInt(75)); } catch (Exception ignored) {}
                    newlyEquipped.add(oid);
                    ForgeTracker.debug("coordEquip slot=" + slot + " level=" + targetLevel + " name=" + targetName);
                    break;
                }
            }
        } catch (Exception e) {
            ForgeTracker.debug("equipTargetLevel ERROR: " + e);
        }
    }

    private static float _lastLoggedAmount = -999f;
    private static float _lastLoggedPromo  = -999f;
    private static float _prevTickAmount   = -1f;
    private static int   _postResetGrace   = 0;  // ticks to suppress heat pool after distribution

    /**
     * Returns the accumulated stage heat pool for the local player.
     * Returns -1 if not in a dungeon level (e.g. town), 0 if no heat picked up yet.
     */

    /**
     * The dungeon director, via the ctx accessor discovered at build time
     * (MappingsNames.DUNGEON_DIRECTOR_METHOD). Falls back to scanning for a 0-arg method
     * whose return type sits in the dungeon.client package, so a stale generated name
     * still resolves. Null in town.
     */
    private static Object dungeonDirector(Object ctx) {
        if (ctx == null) return null;
        try {
            return ctx.getClass().getMethod(MappingsNames.DUNGEON_DIRECTOR_METHOD).invoke(ctx);
        } catch (Exception ignored) {
        }
        try {
            for (java.lang.reflect.Method m : ctx.getClass().getMethods()) {
                if (m.getParameterCount() == 0
                        && m.getReturnType().getName().startsWith("com.threerings.projectx.dungeon.client.")) {
                    return m.invoke(ctx);
                }
            }
        } catch (Exception ignored) {
        }
        return null;
    }

    public static float getStageHeatPool(Object ctx, Object playerObject) {
        try {
            // ctx.GD() → com.threerings.projectx.dungeon.client.S (dungeon director)
            // Dungeon director: the ctx accessor the Patcher discovered structurally (the
            // one 0-arg method returning a dungeon.client type). Matching the RETURN TYPE
            // NAME is what broke on 2026-07-30 — that class went S -> T.
            Object dungeonDir = dungeonDirector(ctx);
            if (dungeonDir == null) return -1f;

            // dungeonDir.bY(LevelPartyObject.class) → LevelPartyObject (null when in town)
            Class<?> lpoClass = Class.forName("com.threerings.projectx.dungeon.data.LevelPartyObject");
            Object lpo = null;
            for (java.lang.reflect.Method m : dungeonDir.getClass().getMethods()) {
                Class<?>[] p = m.getParameterTypes();
                if (p.length == 1 && p[0] == Class.class) {
                    lpo = m.invoke(dungeonDir, lpoClass);
                    break;
                }
            }
            if (!lpoClass.isInstance(lpo)) return -1f;

            // lpo.heat → DSet<Heat>
            Object heatSet = lpoClass.getField("heat").get(lpo);
            if (heatSet == null) return 0f;

            // Walk Heat entries to find the one for this player; log all entries on change
            int playerOid = getPlayerOid(playerObject);
            float myAmount = 0f, myPromo = 0f;
            boolean found = false;
            StringBuilder allEntries = new StringBuilder();
            for (Object entry : (Iterable<?>) heatSet) {
                int oid    = getPlayerOidFromEntry(entry);
                float amt  = entry.getClass().getField("amount").getFloat(entry);
                float prmo = entry.getClass().getField("promoAmount").getFloat(entry);
                allEntries.append(" [oid=").append(oid).append(" amt=").append(amt)
                          .append(" promo=").append(prmo).append("]");
                if (oid == playerOid) { myAmount = amt; myPromo = prmo; found = true; }
            }
            if (!found) return 0f;
            // Detect heat reset: pool drops from positive to zero (server distributed)
            if (_prevTickAmount > 0.5f && myAmount < 0.5f) {
                int floor = 0, actualFloor = 0, actualGateId = 0;
                try { floor       = lpoClass.getField("floor").getInt(lpo); } catch (Exception ignored2) {}
                try { actualFloor = lpoClass.getField("actualFloor").getInt(lpo); } catch (Exception ignored2) {}
                try { actualGateId= lpoClass.getField("actualGateId").getInt(lpo); } catch (Exception ignored2) {}
                _lastLoggedAmount = -999f; // force next log
                _postResetGrace = 20;     // suppress heat pool for ~4 s while floor transitions
            }
            _prevTickAmount = myAmount;
            if (_postResetGrace > 0) {
                _postResetGrace--;
                return 0f;
            }
            return myAmount + myPromo;
        } catch (Exception e) {
            ForgeTracker.debug("getStageHeatPool ERROR: " + e);
            return -1f;
        }
    }

    /**
     * The active LevelPartyObject (dungeon floor state), or null if not in a level
     * (town/arena). Mirrors getStageHeatPool: ctx.GD() -> dungeon director S, then
     * S.bY(LevelPartyObject.class). Exposes floor/actualFloor/actualGateId/
     * pendingFloorName/floorType for floor identification.
     */
    public static Object getLevelPartyObject(Object ctx) {
        try {
            if (ctx == null) return null;
            // Dungeon director: the ctx accessor the Patcher discovered structurally (the
            // one 0-arg method returning a dungeon.client type). Matching the RETURN TYPE
            // NAME is what broke on 2026-07-30 — that class went S -> T.
            Object dungeonDir = dungeonDirector(ctx);
            if (dungeonDir == null) return null;
            Class<?> lpoClass = Class.forName("com.threerings.projectx.dungeon.data.LevelPartyObject");
            for (java.lang.reflect.Method m : dungeonDir.getClass().getMethods()) {
                Class<?>[] p = m.getParameterTypes();
                if (p.length == 1 && p[0] == Class.class) {
                    Object lpo = m.invoke(dungeonDir, lpoClass);
                    return lpoClass.isInstance(lpo) ? lpo : null;
                }
            }
        } catch (Exception e) {}
        return null;
    }

    private static int getPlayerOidFromEntry(Object entry) {
        Class<?> cls = entry.getClass();
        while (cls != null) {
            try {
                java.lang.reflect.Field f = cls.getDeclaredField("_playerOid");
                f.setAccessible(true);
                return f.getInt(entry);
            } catch (NoSuchFieldException ignored) {
                cls = cls.getSuperclass();
            } catch (Exception e) {
                return -1;
            }
        }
        return -1;
    }

    private static boolean _heatBonusLogged = false;

    /**
     * Computes projected heat progress after applying shareHeat to the item.
     * Calls item.a(configMgr, shareHeat) — a pure computation in the game itself.
     * Returns current heat progress if the method cannot be found.
     */
    public static float projectHeatProgress(Object levelItem, Object configMgr, float shareHeat) {
        try {
            if (!_heatBonusLogged && shareHeat > 0f) {
                _heatBonusLogged = true;
                // Log _heatBonus and projected result to diagnose per-item bonus
                float bonus = 0f;
                try {
                    Class<?> cls = levelItem.getClass();
                    while (cls != null) {
                        try { java.lang.reflect.Field bf = cls.getDeclaredField("_heatBonus");
                              bf.setAccessible(true); bonus = bf.getFloat(levelItem); break;
                        } catch (NoSuchFieldException e2) { cls = cls.getSuperclass(); }
                    }
                } catch (Exception ignored2) {}
                float current = getHeatProgress(levelItem);
            }
            Class<?> cfgMgrClass = Class.forName("com.threerings.config.ConfigManager");
            for (java.lang.reflect.Method m : levelItem.getClass().getMethods()) {
                Class<?>[] params = m.getParameterTypes();
                if (params.length == 2 && cfgMgrClass.isAssignableFrom(params[0]) &&
                        params[1] == float.class && m.getReturnType() == float.class) {
                    return (Float) m.invoke(levelItem, configMgr, shareHeat);
                }
            }
        } catch (Exception ignored) {}
        return getHeatProgress(levelItem);
    }

    public static void addWindowToRoot(Object ctx, Object window) {
        try {
            Object root = ctx.getClass().getMethod("getRoot").invoke(ctx);
            for (java.lang.reflect.Method m : root.getClass().getMethods()) {
                if ("addWindow".equals(m.getName()) && m.getParameterCount() == 1) {
                    m.invoke(root, window);
                    return;
                }
            }
            throw new RuntimeException("Cannot find addWindow on " + root.getClass());
        } catch (RuntimeException e) { throw e; }
        catch (Exception e) { throw new RuntimeException(e); }
    }

    /** Returns the item's _heatProgress value (0.0 = no heat, 1.0 = full / forgeable). */
    public static float getHeatProgress(Object levelItem) {
        try {
            java.lang.reflect.Field f = levelItem.getClass().getDeclaredField("_heatProgress");
            f.setAccessible(true);
            return f.getFloat(levelItem);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    /** Returns true when the item's heat bar is full (heatProgress >= 1.0) and it can be forged. */
    public static boolean isHeatReady(Object levelItem) {
        return getHeatProgress(levelItem) >= 1.0f;
    }

    /** Navigates item config to return crystalsNeeded[max] for the item's current forge tier.
     *  Returns -1 if the item has no forge config or is not forgeable. */
    public static int getForgeMaxCrystals(Object levelItem, Object configMgr) {
        try {
            Class<?> cfgMgrClass    = Class.forName("com.threerings.config.ConfigManager");
            Class<?> levelCfgClass  = Class.forName("com.threerings.projectx.item.config.ItemConfig$Level");
            Class<?> forgePropClass = Class.forName("com.threerings.projectx.item.config.ForgePropertyConfig");
            Class<?> cfgRefClass    = Class.forName("com.threerings.config.ConfigReference");

            // item.a(ItemConfig$Level.class, configMgr) → ItemConfig$Level
            Object levelConfig = null;
            for (java.lang.reflect.Method m : levelItem.getClass().getMethods()) {
                Class<?>[] p = m.getParameterTypes();
                if (p.length == 2 && p[0] == Class.class && cfgMgrClass.isAssignableFrom(p[1])) {
                    levelConfig = m.invoke(levelItem, levelCfgClass, configMgr);
                    break;
                }
            }
            if (levelConfig == null) return -1;

            // levelConfig.Q(configMgr) → LevelItemProps (method returning ItemProps subclass)
            Object levelItemProps = null;
            for (java.lang.reflect.Method m : levelConfig.getClass().getMethods()) {
                Class<?>[] p = m.getParameterTypes();
                if (p.length == 1 && cfgMgrClass.isAssignableFrom(p[0])
                        && m.getReturnType().getName().contains("ItemProps")) {
                    levelItemProps = m.invoke(levelConfig, configMgr);
                    break;
                }
            }
            if (levelItemProps == null) return -1;

            // props.forgeProperty (stable field name)
            Object forgePropertyRef = levelItemProps.getClass().getField("forgeProperty").get(levelItemProps);
            if (forgePropertyRef == null) return -1;

            // configMgr.a(ForgePropertyConfig.class, forgePropertyRef) → ForgePropertyConfig
            Object forgeCfg = null;
            for (java.lang.reflect.Method m : configMgr.getClass().getMethods()) {
                Class<?>[] p = m.getParameterTypes();
                if (p.length == 2 && p[0] == Class.class && cfgRefClass.isAssignableFrom(p[1])) {
                    forgeCfg = m.invoke(configMgr, forgePropClass, forgePropertyRef);
                    break;
                }
            }
            if (forgeCfg == null) return -1;

            // props is a public ForgeProps[] directly on ForgePropertyConfig. A
            // game update (v20260717…) removed the old $Original implementation
            // indirection (forgeCfg.K(configMgr).props); the forge window now
            // reads getConfig(...).props straight off the resolved config, so we
            // mirror that.
            Object[] propsArr = (Object[]) forgeCfg.getClass().getField("props").get(forgeCfg);
            int rawLevel = getItemRawLevel(levelItem);
            if (propsArr == null || rawLevel >= propsArr.length) {
                ForgeTracker.debug("getForgeMaxCrystals: props "
                        + (propsArr == null ? "null" : "len " + propsArr.length) + " rawLevel " + rawLevel);
                return -1;
            }
            Object forgeProps = propsArr[rawLevel];
            if (forgeProps == null) return -1;

            // forgeProps.crystalsNeeded[last] (stable field name)
            int[] crystalsNeeded = (int[]) forgeProps.getClass().getField("crystalsNeeded").get(forgeProps);
            if (crystalsNeeded == null || crystalsNeeded.length == 0) return -1;
            return crystalsNeeded[crystalsNeeded.length - 1];
        } catch (Exception e) {
            // Surface the cause: a -1 here silently skips the item in Forge All,
            // so an obfuscation/structure change must not fail invisibly again.
            ForgeTracker.debug("getForgeMaxCrystals failed: " + e);
            return -1;
        }
    }

public static void callEquipService(Object itemService, long oid, int slot, Object listener) {
        try {
            Class<?> listenerClass = Class.forName(CONFIRM_LISTENER_CLASS);
            itemService.getClass().getMethod(SERVICE_EQUIP_METHOD, long.class, int.class, listenerClass)
                .invoke(itemService, oid, slot, listener);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    // ── Listener proxies ──────────────────────────────────────────────────────

    /** Captures the raw forge result object for bonus detection. */
    public static Object createForgeResultListenerProxy(final boolean[] done, final Object[] resultHolder) {
        try {
            Class<?> listenerClass = Class.forName(RESULT_LISTENER_CLASS);
            return java.lang.reflect.Proxy.newProxyInstance(
                Mappings.class.getClassLoader(),
                new Class<?>[]{listenerClass},
                new java.lang.reflect.InvocationHandler() {
                    public Object invoke(Object proxy, java.lang.reflect.Method method, Object[] args) {
                        // requestProcessed(Object result) has a non-String first param
                        if (args != null && args.length > 0
                                && method.getParameterTypes()[0] != String.class) {
                            resultHolder[0] = args[0];
                        }
                        done[0] = true;
                        return null;
                    }
                }
            );
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    /**
     * Wraps an existing ResultListener so individual (non-loop) forge button clicks are also
     * tracked. Forwards every call to {@code original} unchanged, then on success spawns a
     * background thread to record the forge event in ForgeTracker.
     */
    public static Object createChainingForgeListener(final Object original,
                                                      final long oid,
                                                      final int levelBefore,
                                                      final int crystals,
                                                      final int starLevel,
                                                      final Object ctx) {
        try {
            Class<?> listenerClass = Class.forName(RESULT_LISTENER_CLASS);
            return java.lang.reflect.Proxy.newProxyInstance(
                Mappings.class.getClassLoader(),
                new Class<?>[]{listenerClass},
                new java.lang.reflect.InvocationHandler() {
                    public Object invoke(Object proxy, java.lang.reflect.Method method, Object[] args)
                            throws Throwable {
                        method.invoke(original, args);
                        if (args != null && args.length > 0
                                && method.getParameterTypes()[0] != String.class) {
                            final Object result = args[0];
                            new Thread(() -> {
                                try {
                                    Object po = getPlayerObject(ctx);
                                    ForgeTracker.recordForge(
                                        getKnightName(po),
                                        getItemNameByOid(po, oid),
                                        oid, levelBefore + 1, extractLevelAfter(result, levelBefore + 1),
                                        extractForgeDoubleLevel(result), extractForgeHeatBonus(result),
                                        extractForgeBox(result), crystals, getCrystalName(starLevel),
                                        ForgeTracker.dumpResult(result));
                                } catch (Throwable t) {
                                    ForgeTracker.debug("chainingListener bg ERROR: " + t);
                                }
                            }).start();
                        }
                        return null;
                    }
                }
            );
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static String getItemNameByOid(Object playerObject, long oid) {
        try {
            for (Object item : getPlayerItems(playerObject)) {
                if (getItemOid(item) == oid) return getItemName(item);
            }
        } catch (Exception e) {}
        return "Unknown";
    }

    public static boolean extractForgeHeatBonus(Object result) {
        return result instanceof String && ((String) result).contains("m.forge_heat_bonus");
    }

    public static boolean extractForgeDoubleLevel(Object result) {
        return result instanceof String && ((String) result).contains("m.forge_skip");
    }

    public static int extractForgeBox(Object result) {
        if (!(result instanceof String)) return 0;
        String s = (String) result;
        int count = 0, idx = 0;
        while ((idx = s.indexOf("m.forge_prize_box", idx)) >= 0) { count++; idx += 17; }
        return count;
    }

    /** Extracts the new level from the result string (~N is 1-indexed display; we return raw 0-indexed). */
    public static int extractLevelAfter(Object result, int levelBefore) {
        if (result instanceof String) {
            String s = (String) result;
            int idx = s.indexOf("m.forge_new_level");
            if (idx >= 0) {
                int tilde = s.indexOf("~", idx);
                if (tilde >= 0) {
                    int end = tilde + 1;
                    while (end < s.length() && Character.isDigit(s.charAt(end))) end++;
                    try { return Integer.parseInt(s.substring(tilde + 1, end)); }
                    catch (NumberFormatException e) {}
                }
            }
        }
        return levelBefore;
    }

    public static Object createResultListenerProxy(final boolean[] flag) {
        return createResultListenerProxy(flag, null);
    }

    public static Object createResultListenerProxy(final boolean[] flag, final String logPrefix) {
        try {
            Class<?> listenerClass = Class.forName(RESULT_LISTENER_CLASS);
            return java.lang.reflect.Proxy.newProxyInstance(
                Mappings.class.getClassLoader(),
                new Class<?>[]{listenerClass},
                new java.lang.reflect.InvocationHandler() {
                    public Object invoke(Object proxy, java.lang.reflect.Method method, Object[] args) {
                        flag[0] = true;
                        if (logPrefix != null) {
                            if (args != null && args.length > 0 && args[0] != null) {
                                SocketInputState.displayChat(logPrefix + " " + args[0], "attention");
                            } else {
                                SocketInputState.displayChat(logPrefix + " done", "feedback");
                            }
                        }
                        return null;
                    }
                }
            );
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    public static Object createConfirmListenerProxy(final boolean[] flag, final String name) {
        try {
            Class<?> listenerClass = Class.forName(CONFIRM_LISTENER_CLASS);
            return java.lang.reflect.Proxy.newProxyInstance(
                Mappings.class.getClassLoader(),
                new Class<?>[]{listenerClass},
                new java.lang.reflect.InvocationHandler() {
                    public Object invoke(Object proxy, java.lang.reflect.Method method, Object[] args) {
                        // Match by parameter structure, not obfuscated name:
                        // success method has 0 params; failure method has 1 String param
                        Class<?>[] params = method.getParameterTypes();
                        if (params.length == 0) {
                        } else if (params.length == 1 && params[0] == String.class) {
                        }
                        flag[0] = true;
                        return null;
                    }
                }
            );
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    // ── Generic ctx helpers ───────────────────────────────────────────────────

    /** Calls a no-arg method on ctx by its discovered (possibly obfuscated) name. */
    public static Object callNoArgCtxMethod(Object ctx, String methodName) {
        try { return ctx.getClass().getMethod(methodName).invoke(ctx); }
        catch (Exception e) { throw new RuntimeException(e); }
    }

    /** Gets the social scene-join service from the client manager. */
    public static Object getSocialService(Object clientMgr) {
        try { return getService(clientMgr, Class.forName(SOCIAL_SERVICE_CLASS)); }
        catch (Exception e) { throw new RuntimeException(e); }
    }

    /**
     * Calls the social join-scene method on the service returned by the client manager.
     * Uses a ConfirmListener proxy so no reference to the obfuscated chat-adapter class is needed.
     */
    public static void callSocialJoin(Object clientMgr, com.threerings.util.Name friendName) {
        try {
            Object svc = getSocialService(clientMgr);
            Class<?> confirmCls = Class.forName(CONFIRM_LISTENER_CLASS);
            boolean[] done = new boolean[]{false};
            Object listener = createConfirmListenerProxy(done, "AutoJoin");
            svc.getClass()
                .getMethod(SOCIAL_JOIN_METHOD, com.threerings.util.Name.class, confirmCls)
                .invoke(svc, friendName, listener);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    /**
     * Invites a player (knight Name) to this client's current party — the same
     * {@code PartyObject.partyService.<invite>(name, listener)} call the game's
     * friend-picker invite dialog makes. Pass the marshaller read off the live
     * PartyObject's real-named {@code partyService} field; the obfuscated method
     * name is resolved by the Patcher (dispatch index 2; index 1 is boot).
     */
    public static void callPartyInvite(Object partyService, com.threerings.util.Name knightName) {
        try {
            Class<?> confirmCls = Class.forName(CONFIRM_LISTENER_CLASS);
            boolean[] done = new boolean[]{false};
            Object listener = createConfirmListenerProxy(done, "PartyInvite");
            partyService.getClass()
                .getMethod(PARTY_INVITE_METHOD, com.threerings.util.Name.class, confirmCls)
                .invoke(partyService, knightName, listener);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    // ── Mission launch (endless campaign restart) ──────────────────────────────
    // Real (non-obfuscated) anchors so a game update that reshuffles obfuscated
    // names doesn't break the launch: the marshaller keeps its "MissionMarshaller"
    // name and implements the (obfuscated) service interface in mission.client; the
    // difficulty type is the real DungeonCodes$Difficulty enum.
    private static final String MISSION_MARSHALLER_CLASS = "com.threerings.projectx.mission.data.MissionMarshaller";
    private static final String MISSION_SERVICE_PKG = "com.threerings.projectx.mission.client.";
    private static final String DIFFICULTY_CLASS = "com.threerings.projectx.dungeon.data.DungeonCodes$Difficulty";

    /**
     * Launches a gate mission by id (e.g. "shadow_beast") on a difficulty enum
     * constant ("HARD" = in-game Elite), replicating the client's play call captured
     * live from the UI: {@code missionService.a(missionId, Difficulty, b1, b2, b3,
     * ConfirmListener)}. For a PRIVATE (friends/guild-only) party — what the multibox
     * wants, so only the auto-joining alts come in — pass b1=b2=b3=true (public was
     * all-false, solo was true/false/false). The service interface + play method are
     * resolved structurally (stable MissionMarshaller name + the 6-arg signature),
     * not by obfuscated name.
     */
    public static void launchMission(Object ctx, String missionId, String difficultyName,
            boolean b1, boolean b2, boolean b3) {
        try {
            Object clientMgr = getClientManager(ctx);
            Class<?> marshaller = Class.forName(MISSION_MARSHALLER_CLASS);
            Class<?> svcInterface = null;
            for (Class<?> itf : marshaller.getInterfaces()) {
                if (itf.getName().startsWith(MISSION_SERVICE_PKG)) { svcInterface = itf; break; }
            }
            if (svcInterface == null)
                throw new RuntimeException("mission service interface not found on " + marshaller.getName());
            Object svc = getService(clientMgr, svcInterface);
            Class<?> diffCls = Class.forName(DIFFICULTY_CLASS);
            Object difficulty = enumConstant(diffCls, difficultyName);
            Class<?> confirmCls = Class.forName(CONFIRM_LISTENER_CLASS);
            boolean[] done = new boolean[]{false};
            Object listener = createConfirmListenerProxy(done, "LaunchMission");
            java.lang.reflect.Method play = null;
            for (java.lang.reflect.Method m : svc.getClass().getMethods()) {
                Class<?>[] p = m.getParameterTypes();
                if (p.length == 6 && p[0] == String.class && p[1] == diffCls
                        && p[2] == boolean.class && p[3] == boolean.class && p[4] == boolean.class
                        && p[5] == confirmCls) { play = m; break; }
            }
            if (play == null)
                throw new RuntimeException("mission play method (String,Difficulty,Z,Z,Z,listener) not found on "
                        + svc.getClass().getName());
            play.invoke(svc, missionId, difficulty, Boolean.valueOf(b1), Boolean.valueOf(b2),
                    Boolean.valueOf(b3), listener);
        } catch (Exception e) { throw new RuntimeException(e); }
    }

    /** The enum constant of {@code enumCls} whose name() equals {@code name}, or throws. */
    private static Object enumConstant(Class<?> enumCls, String name) {
        Object[] consts = enumCls.getEnumConstants();
        if (consts != null)
            for (Object c : consts)
                if (c instanceof Enum && ((Enum<?>) c).name().equals(name))
                    return c;
        throw new RuntimeException("enum constant '" + name + "' not found in " + enumCls.getName());
    }

}
